project:
  type: website
  output-dir: docs


website:
  title: "PM566 Final Project"


  navbar:
    left: 
    
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Download Report
      
      
   
      

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

